### ISSUE TITLE
Prompt – Expose model config in the UI

### ISSUE THREAD

**Issue by samulatitude** [latitude-dev/latitude-llm#175]
What?

To avoid errors and confusion, we should expose the model through a user-friendly UI instead of writing it in the code. This is because users may not be familiar with the exact name of the model

https://www.figma.com/design/ODioXiqX8aeDMonsh0HBui/Latitude-Cloud?node-id=575-28156&node-type=frame&t=yZbDgulZA1ff4oCx-11

![Image](https://github.com/user-attachments/assets/1fc86b8e-ac24-4783-bba3-8fe083ea77a0)

**Comment by andresgutgon** [comment]
I think we should update the markdown frontmatter instead of replacing it with these selectors. There are other options 

By frontmatter I mean what's between `---`
```
---
model: gpt4-o
---
```
