### ISSUE TITLE
Add user events

### ISSUE THREAD

**Issue by cesr** [latitude-dev/latitude-llm#182]
### Implementation

I'd love to use Posthog for this as it gives us a lot of precooked metrics

### Events

- [x] Sign up
- [x] Log in
- [x] Create project
- [x] Create evaluation
- [x] Run evaluation prompt
- [x] Create dataset
- [x] Add provider api key
- [x] Invite user
- [x] Create new project version
- [x] Publish new project version
- [ ] Create folder
- [x] Create file
- [x] Run document prompt
- [x] Connect evaluation to document
- [x] Run batch evaluation
- [ ] Visit page
  - [ ] Path in metadata

**Comment by geclos** [comment]
#226

**Comment by cesr** [comment]
Reopening to move these events to the backend
