### ISSUE TITLE
Evaluations – Add result reasoning to metadata

### ISSUE THREAD

**Issue by samulatitude** [latitude-dev/latitude-llm#235]
https://www.figma.com/design/ODioXiqX8aeDMonsh0HBui/Latitude-Cloud?node-id=1827-33413&node-type=frame&t=vQZjDEMz2X9QtqBM-11

![Image](https://github.com/user-attachments/assets/f7ba8a1d-94b0-4be3-91ba-e61f4d5a9aa2)

**Comment by geclos** [comment]
#239
