### ISSUE TITLE
Cannot delete drafts or evaluations

### ISSUE THREAD

**Issue by csansoon** [latitude-dev/latitude-llm#237]
Foreign Key constraints do not allow removing drafts or evaluations (probably more stuff too)

https://github.com/user-attachments/assets/4a22e2ef-8f74-48ac-b761-fdf75ac877ac

**Comment by cesr** [comment]
This is duplicated https://github.com/orgs/latitude-dev/projects/2/views/4?pane=issue&itemId=83277995&issue=latitude-dev%7Clatitude-llm%7C376
