### ISSUE TITLE
Model is not correctly detected from the config section

### ISSUE THREAD

**Issue by csansoon** [latitude-dev/latitude-llm#240]
Model is not correctly detected from the config section when written manually in evaluations.

https://github.com/user-attachments/assets/0ddb085d-c88b-4e7f-a30d-7aa2cf264cc4

**Comment by geclos** [comment]
looks like compiler, are u taking a look at this one?

**Comment by csansoon** [comment]
yes! Looking at it rn

**Comment by csansoon** [comment]
I can't seem to reproduce this locally in any way...
