### ISSUE TITLE
Evaluations – Improve import logs data to parameters UI

### ISSUE THREAD

**Issue by samulatitude** [latitude-dev/latitude-llm#241]
What?

Adding data to variables in evaluations can be challenging due to limited space and multiple variables displaying as empty. Design in progress @samulatitude.

[Variables closed](https://www.figma.com/design/ODioXiqX8aeDMonsh0HBui/Latitude-Cloud?node-id=2010-43297&t=WYhtAqXqm4T1Z7Cp-1)

[Variables open](https://www.figma.com/design/ODioXiqX8aeDMonsh0HBui/Latitude-Cloud?node-id=857-37355&t=WYhtAqXqm4T1Z7Cp-1)

![Image](https://github.com/user-attachments/assets/590461cc-99ab-43d3-9696-9682e9b0e0f6)
![Image](https://github.com/user-attachments/assets/6ddf1326-5831-4a9f-88c4-909971dd9f04)

**Comment by geclos** [comment]
bumping priority for this

**Comment by cesr** [comment]
@samulatitude is this design finished?

**Comment by samuperez** [comment]
Not yet, I'll finish today so on Monday it will be ready to implement
