### ISSUE TITLE
Git clone fails on Windows

### ISSUE THREAD

**Issue by antiquechrono** [latitude-dev/latitude-llm#266]
I was hoping to check the project out but cloning the repo fails with the following error.

error: invalid path 'apps/gateway/src/routes/api/v1/projects/:projectId/commits/:commitUuid/documents/handlers/_shared.ts'
error: invalid path 'apps/gateway/src/routes/api/v1/projects/:projectId/commits/:commitUuid/documents/handlers/get.test.ts'
error: invalid path 'apps/gateway/src/routes/api/v1/projects/:projectId/commits/:commitUuid/documents/handlers/get.ts'
error: invalid path 'apps/gateway/src/routes/api/v1/projects/:projectId/commits/:commitUuid/documents/handlers/run.test.ts'
error: invalid path 'apps/gateway/src/routes/api/v1/projects/:projectId/commits/:commitUuid/documents/handlers/run.ts'
error: invalid path 'apps/gateway/src/routes/api/v1/projects/:projectId/commits/:commitUuid/documents/index.ts'

I believe the issue is that : is not a valid path character on Windows.

**Comment by geclos** [comment]
:| oh wow

well, it's an easy fix
