### ISSUE TITLE
Evaluations – Quick UI fixes when selecting an evaluation

### ISSUE THREAD

**Issue by samulatitude** [latitude-dev/latitude-llm#276]
What?

Right now, when selecting an evaluation, it's hard to use:
- Adds page scroll instead of limiting the divs and add overflow: scroll.
- Titles overlap the icon when an evaluation is selected.
- Descriptions have ellipsis instead of showing the full text.

Design

![Image](https://github.com/user-attachments/assets/f927a606-aac0-48f7-bea2-b23f83a11ecb)

**Comment by andresgutgon** [comment]
Maybe also make a bit wider the modal @samulatitude what do you think?
