### ISSUE TITLE
Unable to Scroll on Evaluations Page

### ISSUE THREAD

**Issue by zanbaldwin** [latitude-dev/latitude-llm#322]
Overflow is hidden on `/evaluations` so the page cannot scroll to view the bottom of a long list of evaluations that have been set up, or view the full list of templates.

Update: unable to scroll on any top-level page. Unusable on smaller screens.

**Comment by geclos** [comment]
fixed [here](https://github.com/latitude-dev/latitude-llm/commit/1f32ccdf14038c9821d2652f113d0014d54bac3d)

Thanks for reporting it! This bug was introduced minutes before you noticed it.

**Comment by geclos** [comment]
closing, issue is fixed.
