### ISSUE TITLE
Add human error message when provider name is already taken

### ISSUE THREAD

**Issue by andresgutgon** [latitude-dev/latitude-llm#354]
## What?
```
ConflictError: duplicate key value violates unique constraint "provider_apikeys_name_idx"
```
I think this happens because we don't check in zod schema that the name is taken. And this goes to DB and the constraint throw the error 

### Sentry issue
https://latitude-l5.sentry.io/issues/5955741904/?alert_rule_id=15461351&alert_type=issue&environment=production&notification_uuid=10c428d1-72df-4ee1-8dfb-650b76204c0c&project=4507922531418112&referrer=slack

**Comment by geclos** [comment]
done

**Comment by andresgutgon** [comment]
Where is this fixed?

**Comment by geclos** [comment]
https://github.com/latitude-dev/latitude-llm/pull/355
