### ISSUE TITLE
Reddit spam makes this look SKETCHY AF

### ISSUE THREAD

**Issue by artsyfriedchicken** [latitude-dev/latitude-llm#387]
Your spammy Reddit sponsored posts legit make you look like a scam. And has annoyed me so giving much I'm literally posting here. 

Targeted your ads better and stop spamming everyone. 
I have ZERO interest in LLMs and there is ABSOLUTELY no reason I should have to come across your stupid sponsored comment on EVERY SINGLE POST I CLICK ON REDDIT.

**Comment by geclos** [comment]
Peace out dawg 🤙
