### ISSUE TITLE
SDK response type does not contain object.

### ISSUE THREAD

**Issue by csansoon** [latitude-dev/latitude-llm#400]
![image](https://github.com/user-attachments/assets/0b55ab6a-5867-42c3-b6bd-11b59efa50c5)
(☝️ This is present in the response object, it is just not typed)

![image](https://github.com/user-attachments/assets/213f4be2-3c4e-483c-bd85-0ab313cf7856)

**Comment by geclos** [comment]
hmm the type is a union type including the object so it does include the object it's just that it might or might not exist depending on the response type. We can probably improve those types.
