### ISSUE TITLE
Failed to open localhost:3000

### ISSUE THREAD

**Issue by buweiyuqi** [latitude-dev/latitude-llm#403]
I followed the self-hosted guide to deploy the platform. After the environments were successfully set up and the docker compose was up, I entered the url localhost:3000, and it showed a build error as follow:
![WX20241011-172529@2x](https://github.com/user-attachments/assets/0707d72c-1468-4a09-be1b-2e3e99d772f1)

it showed that a dependency was not found. However, I already install all dependencies by pnpm. 

Any idea to fix it? Thanks a lot!

**Comment by geclos** [comment]
woops your a missing a build step.

`pnpm build --filter='./packages/**'` this should do it (if you could update the docs it would be awesome)

**Comment by buweiyuqi** [comment]
> woops your a missing a build step.
> 
> `pnpm build --filter='./packages/**'` this should do it (if you could update the docs it would be awesome)

Works for me. Thx.

I will try to update the docs and commit it.
