### ISSUE TITLE
Specify that the "daily free runs" only apply to the default provider.

### ISSUE THREAD

**Issue by csansoon** [latitude-dev/latitude-llm#418]
When the user selects the default “Latitude” provider, a message appears stating they have 100 daily free runs.
However, it is always the default provider when creating a new prompt, so the message always displays. It doesn’t clarify that this limit applies only to this provider, instead of overall runs, which can be confusing

**Comment by SergioMD15** [comment]
On top of this, it's not very clear how to add a new provider from this section
