### ISSUE TITLE
Evaluation Result Document log info modal does not return the messages

### ISSUE THREAD

**Issue by andresgutgon** [latitude-dev/latitude-llm#476]
# What?
Doing an evaluation result if you click on "Check original". Messages of the original document log are not displayed. 

This is a regression introduced here 
https://github.com/latitude-dev/latitude-llm/pull/381

<img width="939" alt="image" src="https://github.com/user-attachments/assets/66e6d1a9-65de-477b-9bee-56dab4eeea96">

**Comment by geclos** [comment]
fixed
