### ISSUE TITLE
Editor layout breaks

### ISSUE THREAD

**Issue by cesr** [latitude-dev/latitude-llm#516]
![Image](https://github.com/user-attachments/assets/df97f6f3-c86c-4eaa-8088-e4bda3b5372f)

**Comment by neoxelox** [comment]
To reproduce the bug import a prompt file, which has a system tag inside, within a system tag, Ex.:

```svelte
<system>
<prompt path="/WeekMenuChef/weekchef-base-instructions" />
</system>
```
