### ISSUE TITLE
Support for documents in parameters

### ISSUE THREAD

**Issue by cesr** [latitude-dev/latitude-llm#597]
- Ability to upload files in the playground
- Support for pdf, tsv, txt, md
- Files get converted to markdown
- They're embedded in the prompt directly

**Comment by andresgutgon** [comment]
## Some questions
Do we want to store the reference to the file?
Can the see past uploaded documents?
Does really makes sense to allow PDF? Is that a real need for it. 
Maybe we should include in the list Microsoft Word files?
