### ISSUE TITLE
Add refiner button to eval results logs

### ISSUE THREAD

**Issue by cesr** [latitude-dev/latitude-llm#602]
We need to add this button in two places:

1. In each log row, a button at the end that triggers the refiner process based on that evaluation result.
2. Each log row should have a checkbox, when one or multiple logs are selected a button is enabled on the top right of the table to "Refine prompt". Same as the 1st case, it triggers the refiner process based on those evaluation results.

**Comment by andresgutgon** [comment]
PR: https://github.com/latitude-dev/latitude-llm/pull/642
