### ISSUE TITLE
Suggestion editor hard crashes sometimes

### ISSUE THREAD

**Issue by geclos** [latitude-dev/latitude-llm#653]
https://latitude-l5.sentry.io/issues/6079855405/?alert_rule_id=15461351&alert_type=issue&environment=production&notification_uuid=4a91d0a6-735b-4477-bd15-251c7b089d96&project=4507922531418112&referrer=slack

**Comment by andresgutgon** [comment]
already fixed here
https://github.com/latitude-dev/latitude-llm/commit/f03367c18e3fa7c4dc9c0ff95fbe603ed0151bd7
