### ISSUE TITLE
for each loop over a string parameter causes infinite loop in promptl

### ISSUE THREAD

**Issue by geclos** [latitude-dev/latitude-llm#686]
Steps to reproduce:
1. add a variable to a prompt
2. pass a string value to that variable
3. Iterate the string value with a for loop in prompt
4. parsing hangs

**Comment by andresgutgon** [comment]
You say something like this?
<img width="1152" alt="image" src="https://github.com/user-attachments/assets/6d675934-0fa4-4cfa-9079-0df87e4bd63f" />

**Comment by geclos** [comment]
yup
